"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class rl_vae_obs_lcmt(object):
    __slots__ = ["obs", "timestamp"]

    __typenames__ = ["float", "int64_t"]

    __dimensions__ = [[45], None]

    def __init__(self):
        self.obs = [ 0.0 for dim0 in range(45) ]
        self.timestamp = 0

    def encode(self):
        buf = BytesIO()
        buf.write(rl_vae_obs_lcmt._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>45f', *self.obs[:45]))
        buf.write(struct.pack(">q", self.timestamp))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != rl_vae_obs_lcmt._get_packed_fingerprint():
            raise ValueError("Decode error")
        return rl_vae_obs_lcmt._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = rl_vae_obs_lcmt()
        self.obs = struct.unpack('>45f', buf.read(180))
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if rl_vae_obs_lcmt in parents: return 0
        tmphash = (0x783cfa6a6763c1b9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if rl_vae_obs_lcmt._packed_fingerprint is None:
            rl_vae_obs_lcmt._packed_fingerprint = struct.pack(">Q", rl_vae_obs_lcmt._get_hash_recursive([]))
        return rl_vae_obs_lcmt._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", rl_vae_obs_lcmt._get_packed_fingerprint())[0]

